<a href="https://colab.research.google.com/github/kumarmayank29/50-Startups/blob/main/50Startups.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**This dataset has data collected from New York, California and Florida about 50 business Startups "17 in each state". The variables used in the dataset are Profit, R&D spending, Administration Spending, and Marketing Spending.**

In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import files
uploaded = files.upload()

Saving 50Startup.csv to 50Startup.csv


In [3]:
dataset=pd.read_csv("50Startup.csv")

In [4]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

**Check For NULL Values**


In [5]:
dataset.isnull().any()

R&D Spend          False
Administration     False
Marketing Spend    False
State              False
Profit             False
dtype: bool

In [6]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

**Encode Values which are given as text Using Label Encoder**

In [7]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dataset['State']=le.fit_transform(dataset['State'])

In [8]:
dataset.head()

R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.20       136897.80        471784.10      2  192261.83
1  162597.70       151377.59        443898.53      0  191792.06
2  153441.51       101145.55        407934.54      1  191050.39
3  144372.41       118671.85        383199.62      2  182901.99
4  142107.34        91391.77        366168.42      1  166187.94

In [9]:
dataset['State'].value_counts()

2    17
0    17
1    16
Name: State, dtype: int64

**Apply One Hot Encoding**

Even before that divide this dataset into input and output 

In [10]:

x  = dataset.iloc[:,0:4].values
y = dataset.iloc[:,4:5].values

In [11]:

from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z=one.fit_transform(x[:,3:4]).toarray()
x=np.delete(x,3,axis=1)
x=np.concatenate((z,x),axis=1)

In [12]:
x #Converted to 6 columns after one hot encodimng of columns State

array([[0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.6534920e+05,
        1.3689780e+05, 4.7178410e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.6259770e+05,
        1.5137759e+05, 4.4389853e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.5344151e+05,
        1.0114555e+05, 4.0793454e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.4437241e+05,
        1.1867185e+05, 3.8319962e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.4210734e+05,
        9.1391770e+04, 3.6616842e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.3187690e+05,
        9.9814710e+04, 3.6286136e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 1.3461546e+05,
        1.4719887e+05, 1.2771682e+05],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 1.3029813e+05,
        1.4553006e+05, 3.2387668e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, 1.2054252e+05,
        1.4871895e+05, 3.1161329e+05],
       [1.0000000e+00, 0.0000000e+00,

In [13]:
x.shape

(50, 6)

**Split the Data**

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

**ANN Starts**

In [15]:
from keras.models import Sequential
from keras.layers import Dense

In [16]:
x_train.shape

(40, 6)

In [18]:
#Declare the model
model=Sequential()
#Add input Layer
model.add(Dense(units=6,activation='relu'))
#Add hidden Layers
model.add(Dense(units=12,activation='relu'))
#Add the Output Layer
model.add(Dense(units=1,activation='relu'))

In [19]:
model.compile(optimizer='adam',loss='mse',metrics=["mse"])

**Fit the Model**

In [20]:
model.fit(x_train,y_train,epochs=700,batch_size=8)

Epoch 1/700
5/5 [==============================] - 1s 2ms/step - loss: 1653572864.0000 - mse: 1653572864.0000
Epoch 2/700
5/5 [==============================] - 0s 1ms/step - loss: 1418792512.0000 - mse: 1418792512.0000
Epoch 3/700
5/5 [==============================] - 0s 1ms/step - loss: 1197381557.3333 - mse: 1197381557.3333
Epoch 4/700
5/5 [==============================] - 0s 1ms/step - loss: 805497738.6667 - mse: 805497738.6667
Epoch 5/700
5/5 [==============================] - 0s 2ms/step - loss: 520059552.0000 - mse: 520059552.0000
Epoch 6/700
5/5 [==============================] - 0s 1ms/step - loss: 395151722.6667 - mse: 395151722.6667
Epoch 7/700
5/5 [==============================] - 0s 1ms/step - loss: 256298722.6667 - mse: 256298722.6667
Epoch 8/700
5/5 [==============================] - 0s 2ms/step - loss: 266323242.6667 - mse: 266323242.6667
Epoch 9/700
5/5 [==============================] - 0s 1ms/step - loss: 215109194.6667 - mse: 215109194.6667
Epoch 10/700
5/5 [====

In [21]:
y_pred=model.predict(x_test)

**Check on Random Value**

In [36]:
y_p=model.predict(np.array([[1,0,0,12345,13456,12345]]))

In [37]:
y_p

array([[13250.532]], dtype=float32)

In [24]:
y_pred

array([[114619.875],
       [118906.08 ],
       [123706.766],
       [ 64075.848],
       [171102.75 ],
       [126289.06 ],
       [ 55547.02 ],
       [ 98092.086],
       [119966.125],
       [156356.5  ]], dtype=float32)

In [29]:
y_test

array([[103282.38],
       [144259.4 ],
       [146121.95],
       [ 77798.83],
       [191050.39],
       [105008.31],
       [ 81229.06],
       [ 97483.56],
       [110352.25],
       [166187.94]])

In [34]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
print("Mean square Error is ",mean_squared_error(y_test, y_pred))
print("R2-Score is ",r2_score(y_test, y_pred))



Mean square Error is  316189053.79247016
R2-Score is  0.752763208764241
